# Generated by Django 5.0.6 on 2026-08-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('total_miles_driving', models.FloatField(default=0.0)),
                ('total_mileage', models.FloatField(default=0.0)),
                ('remarks', models.JSONField(default=list)),
                ('recap_hours', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_duration_hours', models.FloatField(default=0.0)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.dailylog')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('start', 'Start / Pre-trip'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest_break', '30-Minute Break'), ('mandatory_rest', '10-Hour Rest'), ('fuel', 'Fuel Stop')], max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0.0)),
                ('mile_marker', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
